services:
  ragapp:
    build: .
    container_name: ragapp_api
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    restart: always
    ports:
      - "10000:10000" # Blob storage
    command: "azurite --blobHost 0.0.0.0"
    volumes:
      - azurite_data:/data

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: ragapp_ui
    restart: always
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    depends_on:
      - ragapp

  db:
    image: postgres:13
    container_name: ragapp_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ragapp_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333" # gRPC
      - "6334:6334" # HTTP
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  ragapp_data:
  azurite_data:
  qdrant_data:
