services:
  ragapp:
    build: .
    container_name: ragapp
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: ragapp_ui
    restart: always
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app/ui
      - ./src:/app/src
    depends_on:
      - ragapp

  db:
    image: postgres:13
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ragapp_data:/var/lib/postgresql/data

volumes:
  ragapp_data:
